<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CartButton</name>
   <tag></tag>
   <elementGuidId>65f0934b-0f21-4e38-a78a-9357e7ab0185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hlb-view-cart</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
